routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'WebController@index');

Route::get('/productos/{id}', 'WebController@productos');

Route::get('/perfil', 'WebController@userSection');

Route::get('/productos/{id}/details', 'WebController@pDetails');

Route::get('/promociones/{id}/details', 'WebController@proDetails');

Route::get('/servicios/{name}/{id}', 'WebController@sDetails');

Route::get('/giftcards/{id}', 'WebController@gDetails');

Route::get('/servicios/{name}', 'WebController@servicios');

Route::get('/contacto', 'WebController@contacto');

Route::get('/promociones', 'WebController@promociones');

Route::get('/giftcards', 'WebController@giftcards');

Auth::routes();

Route::get('/logOut', function(){
	Auth::logout();
	return Redirect::back();
});

Route::get('/home', 'HomeController@index');

//Route::get('/administrador', 'AdminController@login');

Route::get('/administrador/dashboard', 'AdminController@index');

Route::get('/administrador/productos', 'AdminController@products');

Route::get('/administrador/categorias', 'AdminController@categories');

Route::get('/administrador/servicios', 'AdminController@services');

Route::get('/administrador/usuarios', 'AdminController@users');

Route::get('/administrador/clientes', 'AdminController@clients');

Route::get('/administrador/agenda', 'AdminController@schedule');

Route::get('/administrador/giftcards', 'AdminController@giftcards');

Route::get('/administrador/promociones', 'AdminController@promociones');

Route::get('/administrador/ventas', 'AdminController@sales');

Route::get('/administrador/flujo_caja', 'AdminController@cashFlow');

Route::resource('/products','ProductsController');

Route::resource('/imagesApp','ImagesController');

Route::resource('/categories','CategoryController');

Route::resource('/user_history', 'UserHistoryController');

Route::post('/categories/addBox','CategoryController@addBox');

Route::get('/categories/deleteBox/{id}/{category}','CategoryController@deleteBox');

Route::resource('/services','ServicesController');

Route::resource('/users','UserController');

Route::resource('/giftcardsApp','GiftCardController');

Route::resource('/promotions','PromotionController');

Route::resource('/cartApp','CartController');

Route::resource('/sales','SalesController');

Route::get('/getHoursByDate/{date}/{item}', 'ScheduleController@getHoursByDate');

Route::resource('/schedules','ScheduleController');

Route::get('/goDahsboard/{store}', 'AdminController@goDahsboard');

Route::get('/goStore/{store}', 'WebController@goStore');

Route::get('/goTransbank', 'CartController@goTransbank');

Route::get('/goTransbankResponse', 'CartController@goTransbankResponse');

Route::post('/goTransbankResponse', 'CartController@goTransbankResponse');

Route::post('/goTransbankFinish', 'CartController@goTransbankFinish');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');

Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

Route::get('web/getService/{id}', 'WebController@getService');
Route::get('web/getService2/{id}', 'WebController@getService2');
Route::post('web/reservationRequest', 'WebController@reservationRequest');

Route::post('web/contact', 'WebController@contact');

Route::get('/cartClean', 'CartController@clear');

Route::get('/users/estetic/{store_id}', 'UserController@estetic');

Route::post('/getDoctorsByDate', 'WebController@getDoctorsByDate');

Route::post('/schedules/clientStore', 'ScheduleController@clientStore');

Route::get('/tratamiento/{id}','WebController@tratamientos');

Route::get('/tratamiento/{id}/{sub}','WebController@subtratamientos');

Route::post('/categoryImgApp/{id}', 'CategoryController@categoryImgApp');

Route::get('/categories/getSubCategories/{id}', 'CategoryController@getSubCategories');

Route::post('/categories/addSub', 'CategoryController@addSub');

Route::get('/categories/deleteSub/{id}/{category}','CategoryController@deleteSub');

Route::get('/categoriesServices', 'CategoryController@categoriesServices');

Route::get('/administrador/cashFlowEgresos/{type}/{id}', 'AdminController@cashFlowEgresos');

Route::post('/administrador/cashFlowEgresos/{type}/{id}', 'AdminController@cashFlowEgresosP');

Route::get('/administrador/cashFlowIngresos/{type}/{id}', 'AdminController@cashFlowIngresos');

Route::post('/administrador/cashFlowIngresos/{type}/{id}', 'AdminController@cashFlowIngresosP');

Route::resource('/expenses', 'ExpensesController');

Route::get('/getCategoryByType/{type}', 'CategoryController@getCategoryByType');

Route::get('/getItemsByType/{type}/{cat}', 'AdminController@getItemsByType');

Route::get('/salesItems/{id}', 'SalesController@salesItems');

Route::get('/getSalesbyUser/{id}', 'SalesController@getSalesbyUser');

Route::get('/saleitem/{id}', 'SalesController@saleitem');

Route::post('/saleItemStatus', 'SalesController@saleItemStatus');

Route::get('/administrador/historial_venta/{id}', 'AdminController@history_sales');

Route::get('/goFlow', 'CartController@goFlow');

Route::post('/flowConfirm', 'CartController@flowConfirm');

Route::post('/flowResult', 'CartController@flowResult');

Route::put('/usersUpdate/{id}', 'UserController@update2');

Route::resource('/administrador/cliente/{id}/tratamientos', 'ClientServiceController');

Route::resource('/administrador/tratamientosFicha', 'PatientFileController');

Route::get('/venta', 'UserController@ventaT');

Route::get('/serviceFindBySubcategory/{id}', 'ServicesController@findBySubcategory');

Route::post('/clientService', 'ServicesController@clientService');

Route::post('/subirConsentimiento', 'ClientServiceController@subirConsentimiento');

Route::resource('/clientServices', 'ClientServiceController');

app/Models/Promotion.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Promotion extends Model
{
    protected $fillable = ['name', 'description', 'price', 'type', 'category_id','store_id', 'before_price' ];

	public $typeArray = [
		0=>'Productos',1=>'Servicios'
	];

	public function store()
	{
		return $this->belongsTo('App\Models\Store');
	}
	public function images()
	{
		return $this->hasOne('App\Models\Image','foreign_id')->where('type', 4);
	}
	public function category()
	{
		return $this->belongsTo('App\Models\Category');
	}
}

app/Http/Controllers/PromotionController.php
<?php

namespace App\Http\Controllers;

use App\Models\{Promotion, Image};
use Illuminate\Http\Request;

class PromotionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
		return Promotion::with('store','category')
						->where('store_id', \Session::get('store_id'))
						->orderBy('id','DESC')
						->get();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $store = Store::find(\Session::get('store_id'));
      $stores = Store::pluck('name', 'id');
      $categories = Category::where('store_id', $store->id)->where('type',2)->pluck('name', 'id');
      return view('admin.promotions.crearModal', ['promotion'=> new Promotion(), 'categories'=>$categories,'store'=>$store,'stores'=>$stores]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    $promotion = Promotion::create($request->all());

		if ($request->file('file')) {
			$file = $request->file('file');
			$destinationPath = 'uploads/promotions';
			$hashImage = str_random(30);
			$ext = $file->getClientOriginalExtension();
			$file->move($destinationPath,"$hashImage.$ext");
			$image = new Image;
			$image->file = "$hashImage.$ext";
			$image->type = 4;
			$image->foreign_id = $promotion->id;
			$image->save();

		}

    
    return back()->with('status', 'Promocion Creada');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return Promotion::with('images','store','category')->find($id);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return Promotion::with('images','store','category')->find($id);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $promotion = Promotion::find($id)->update($request->all());
      
      if ($request->file('file')) {
        $file = $request->file('file');
        $destinationPath = 'uploads/promotions';
        $hashImage = str_random(30);
        $ext = $file->getClientOriginalExtension();
        $file->move($destinationPath,"$hashImage.$ext");
        $image = new Image;
        $image->file = "$hashImage.$ext";
        $image->type = 4;
        $image->foreign_id = $id;
        $image->save();
      }
  
      return back()->with('status', 'Promocion Actualizada');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Promotion  $promotion
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
		  Promotion::find($id)->delete();
      return back()->with('status', 'Promocion Eliminada');
    }
}

resources/views/admin/promotions/crearModal.blade.php
<div class="modal fade" id="createModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Crear Promocion</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form action="{{ route('promotions.store')}}" method="POST" enctype="multipart/form-data">

				@csrf
				<input type="hidden" id="token" value="{{csrf_token()}}">
				<div class="modal-body">					
					<input type="hidden" name="store_id" value="{{$store->id}}">
					<input type="hidden" name="category_id" value="{{$categories->id=13}}">

						<div class="form-group row">
							<div class="col-md-6">
								<label for="file">Portada</label>
								<div class="input-group">
										<input type="file" name="file" class="form-control">
								</div>
							</div>
							<div class="col-md-6">
								<label for="name">Nombre</label>
								<div class="input-group">
										<input type="text" name="name" id="name" class="form-control" placeholder="Nombre">
								</div>
							</div>
						</div>
						<div class="form-group row">
							
							<div class="col-md-6">
								<label for="price">Precio</label>
								<div class="input-group">
										<input type="number" name="price" id="price" class="form-control" placeholder="Precio">
								</div>
							</div>
							<div class="col-md-6">
								<label for="name">Precio Antes</label>
								<div class="input-group">
										<input type="text" name="before_price" id="name" class="form-control" placeholder="Precio Antes">
								</div>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6">
								<label for="category_id">Tipo</label>
								<div class="input-group">
									<select class="form-control" name="type" id="type"  placeholder="type">
										<option>Tipo</option>
											<option value="0">Productos</option>
											<option value="1">Servicios</option>											
									</select>
								</div>
							</div> 
							<div class="col-md-6">
								<label for="store_id">Tienda</label>
								<div class="input-group">
									<select class="form-control" name="store_id" id="store_id"  placeholder="type">
										<option>Tienda</option>
										@foreach ($stores as $key => $value)
											<option value="{{$key}}">{{$value}}</option>
										@endforeach
									</select>
								</div>
							</div> 
						</div>
						<div class="form-group row">         
							<div class="col-md-12">
								<label for="">Descripccion</label>
								<textarea name="description" id="description" class="form-control"></textarea>
							</div>
						</div> 
					<div class=" row col-md-12 text-right">
					  <input type="submit" value="Crear" class="btn btn-danger" style="width:200px">
				  </div>
				</div>
			</form>
		</div>
	</div>
</div>

resources/views/admin/promotions/editModal.blade.php
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Editar Promocion</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<form action="/promotions/$id" method="POST" enctype="multipart/form-data">

				@method('PUT')
				@csrf
				<input type="hidden" id="token" value="{{csrf_token()}}">
				<div class="modal-body">					
					<input type="hidden" name="store_id" value="{{$store->id}}">

						<div class="form-group row">
							<div class="col-md-6">
								<label for="file">Portada</label>
								<div class="input-group">
										<input type="file" name="file" class="form-control">
								</div>
							</div>
							<div class="col-md-6">
								<label for="name">Nombre</label>
								<div class="input-group">
										<input type="text" name="name" id="name" class="form-control" >
								</div>
							</div>
						</div>
						<div class="form-group row">
							
							<div class="col-md-6">
								<label for="price">Precio</label>
								<div class="input-group">
										<input type="number" name="price" id="price" class="form-control">
								</div>
							</div>
							<div class="col-md-6">
								<label for="name">Precio Antes</label>
								<div class="input-group">
										<input type="text" name="before_price" id="before_price" class="form-control" placeholder="Precio Antes">
								</div>
							</div>
						</div>
						<div class="form-group row">
							<div class="col-md-6">
								<label for="category_id">Tipo</label>
								<div class="input-group">
									<select class="form-control" name="type" id="type"  placeholder="type">
										<option>Tipo</option>
											<option value="0">Productos</option>
											<option value="1">Servicios</option>											
									</select>
								</div>
							</div> 
							<div class="col-md-6">
								<label for="category_id">Categoria</label>
								<div class="input-group">
									<select class="form-control" name="category_id" id="category_id"  placeholder="type">
										<option>Tipo</option>
										@foreach ($categories as $key => $value)
											<option  value="{{$key}}">{{$value}}</option>
										@endforeach
									</select>
								</div>
							</div> 
						</div>
						<div class="form-group row">
							<div class="col-md-6">
								<label for="store_id">Tienda</label>
								<div class="input-group">
									<select class="form-control" name="store_id" id="store_id"  placeholder="type">
										<option>Tienda</option>
										@foreach ($stores as $key => $value)
											<option  value="{{$key}}">{{$value}}</option>
										@endforeach
									</select>
								</div>
							</div> 
						</div>
						<div class="form-group row">         
							<div class="col-md-12">
								<label for="">Descripccion</label>
								<textarea name="description" id="description" class="form-control"></textarea>
							</div>
						</div> 
					<div class=" row col-md-12 text-right">
					  <input type="submit" value="Actualizar" class="btn btn-danger" style="width:200px">
				  </div>
				</div>
			</form>
		</div>
	</div>
</div>

resources/views/admin/promotions/editPhoto.blade.php
<div class="modal fade" id="editPortadaModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title" id="exampleModalLabel">Editar Foto</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>

		  	<div class="modal-body">
			  	{!! Form::open(['url' => 'services','files'=>true,'class'=>'form-material']) !!}

					<div class="">
						<img :src="element.portada" alt="" style="width:100%;max-width:400px">
					</div>
					<div class="form-group row">
						<div class="col-md-6">
							{{Form::label('imagenes', 'Portada')}}<br>
							<input type="file" id="file2" ref="file2" v-on:change="handleFileUpload2()"/>
						</div>

					</div>

			  	{!! Form::close() !!}
		  	</div>
		  	<div class="modal-footer">
				<div class="">
					<span v-for="error in errors" class="text-danger">@{{error}}</span>
				</div>
				<button type="button" class="btn btn-primary" v-on:click="submitImage()">Guardar</button>
		  	</div>
		</div>
	</div>
</div>

resources/views/admin/promotions/list.blade.php
@extends('admin.layout')
@section('css')
	<link rel="stylesheet" href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
	<link rel="stylesheet" href="/admin/css/easy-autocomplete.min.css"/>
	<style media="screen">
	.easy-autocomplete-container{
		z-index: 2000;
			position: relative;
	}
	.easy-autocomplete {
		width: 100%!important
	}
	</style>
@endsection
@section('content')
	<div id="mainPromotions" class="">
		<div class="row page-titles">
			<div class="col-md-5 align-self-center">
				<h3 class="text-themecolor">Promociones</h3>
			</div>
			<div class="col-md-7 text-right">
				<a href="#" data-toggle="modal" data-target="#createModal" class="btn waves-effect waves-light btn btn-info pull-right hidden-sm-down">Crear Promocion</a>
			</div>
			
			@if (session('status'))
				<div class="alert alert-success">
					{{ session('status') }}
				</div>
			@endif
		</div>
		<div class="row">
			<div class="col-lg-12">
				<div class="card">
					<div class="card-body">
						<div class="d-flex">
							<div>
								<h5 class="card-title">Lista</h5>
							</div>
						</div>
						<div class="table-responsive m-t-20 no-wrap">
							<table id="myTable" class="table vm no-th-brd pro-of-month table-hover">
								<thead>
									<tr>
										<th>Portada</th>
										<th>Nombre</th>
										<th>Precio Antes</th>
										<th>Precio</th>
										<th>Tipo</th>
										<th>Categoria</th>
										<th>Acciones</th>
									</tr>
								</thead>
								<tbody>
									@foreach ($promotions as $p)
									<tr>
										<td><img src="{{asset('/uploads/promotions/'.$p->images)}}" width="150" /></td>
										<td>{{$p->name}}</td>
										<td>{{$p->before_price}}</td>
										<td>{{$p->price}}</td>
										<td>{{$p->typeName}}</td>
										<td>{{$p->category->name ?? ''}}</td>
										<td>
											<a href="#" class="link m-r-10 edit" data-promotionid="{{$p->id}}">
												<i class="fa fa-pencil-alt"></i>
											</a>
											<form action="/promotions/{{ $p->id }}" method="post" style="float:right">
                                                @csrf
                                                {{ method_field('delete') }}
                                                <button class="btn btn-default" type="submit"style="background:transparent;padding: 0 12px" >
                                                    <i class="fa fa-trash-alt"></i>
                                                </button>
                                            </form>
										</td>
									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	@include('admin.promotions.crearModal')
	@include('admin.promotions.editModal')
	@include('admin.promotions.editPhoto')

@endsection
@section('scripts')

<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="/admin/js/jquery.easy-autocomplete.min.js"></script>

<script type="text/javascript">
	$(document).ready( function () {
	    $('#myTable').DataTable({
			'language': {
		        "decimal": "",
		        "emptyTable": "No hay información",
		        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
		        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
		        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
		        "infoPostFix": "",
		        "thousands": ",",
		        "lengthMenu": "Mostrar _MENU_ Entradas",
		        "loadingRecords": "Cargando...",
		        "processing": "Procesando...",
		        "search": "Buscador:",
		        "zeroRecords": "Sin resultados encontrados",
		        "paginate": {
		            "first": "Primero",
		            "last": "Ultimo",
		            "next": "Siguiente",
		            "previous": "Anterior"
		        }
		    }
		});
		$("#basics2").easyAutocomplete(options2);

	} );

</script>		
	<script>
		$(function(){
          
		  $('body').on('click','.edit',function(){
			var id = $(this).data('promotionid')
			$.get('/promotions/'+id, function(r){
				console.log(r);
				$('#editModal form').attr('action', "/promotions/"+r.id)
                    $('#editModal input[name=name]').val(r.name)
                    $('#editModal input[name=price]').val(r.price)
					$('#editModal input[name=before_price]').val(r.before_price)
					$('#editModal select[name=type]').val(r.type)
					$('#editModal select[name=store_id]').val(r.store_id)
					$('#editModal select[name=category_id]').val(r.category_id)
                    $('#editModal textarea[name=description]').text(r.description)
                    $('#editModal').modal()
			})
		  })
		  $("body").on('click', '.cancelEdit', function(e){
                e.preventDefault()
				location.reload()
			})
        })
	</script>
@endsection